version: '3.7'
services:
  sage-data-api:
    image: iperezx/sage-data-api:latest
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db
    ports:
      - "8080:8080"
    
