apiVersion: apps/v1
kind: Deployment
metadata:
  name: sage-node-api
  namespace: sage
spec:
  replicas: 1
  selector:
    matchLabels:
      k8s-app: sage-node-api
  template:
    metadata:
      labels:
        k8s-app: sage-node-api
    spec:
      containers:
      - name: sage-node-api
        image: iperezx/sage-nodes-api:latest     
        resources:
            limits:
              memory: 100Mi
              cpu: 100m
            requests:
              memory: 100Mi
              cpu: 100m
        ports:
          - name: http
            containerPort: 8080
            protocol: TCP
        imagePullPolicy: Always
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: sage-node-api
  labels:
    service: sage-node-api
spec:
  selector:
    k8s-app: sage-node-api
  ports:
  - name: web
    port: 8080
    protocol: TCP
    targetPort: 8080
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: sage-node-api
  namespace: sage
  annotations:
    traefik.ingress.kubernetes.io/router.tls: ""
spec:
  rules:
  - host: sage-node-api.nautilus.optiputer.net
    http:
      paths:
      - path: /
        backend:
          serviceName: sage-node-api
          servicePort: 8080

