apiVersion: apps/v1
kind: Deployment
metadata:
  name: sage-data-api
  namespace: sage
spec:
  replicas: 1
  selector:
    matchLabels:
      k8s-app: sage-data-api
  template:
    metadata:
      labels:
        k8s-app: sage-data-api
    spec:
      containers:
      - name: sage-data-api
        image: iperezx/sage-data-api:latest     
        resources:
            limits:
              memory: 100Mi
              cpu: 100m
            requests:
              memory: 100Mi
              cpu: 100m
        ports:
          - name: http
            containerPort: 8080
            protocol: TCP
        imagePullPolicy: Always
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: sage-data-api
  labels:
    service: sage-data-api
spec:
  selector:
    k8s-app: sage-data-api
  ports:
  - name: web
    port: 8080
    protocol: TCP
    targetPort: 8080
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: haproxy
  name: sage-data-api
spec:
  rules:
  - host: sage-data-api.nrp-nautilus.io
    http:
      paths:
      - backend:
          service:
            name: sage-data-api
            port:
              number: 8080
        path: /
        pathType: ImplementationSpecific
  tls:
  - hosts:
    - sage-data-api.nrp-nautilus.io
